Cafuv/CafuvSmart/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sesiones.urls'))
]

Cafuv/sesiones/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.http import require_POST
urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user = True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('change/', views.change, name='change'),
    path('usuarios/logged/', views.get_logged_user, name='logged'),
    path('descargar/<int:pk>', views.descargar_archivo, name='descargar'),
    path('activate/<str:uidb64>/<str:token>/<str:grupo>/', views.activate_account, name='activate'),


    path('', views.index_view, name='home'),
    path('eventos/api/', views.ApiEventos),
    path('eventos/<int:pk>', views.EventosFormView.as_view(), name="eventos_form"),



    path('usuarios/', views.usuarios_view, name="usuarios_view"),
    path('usuarios/api/', views.ApiUsuarios),
    path('usuarios/<str:pk>', views.UsuariosFormView.as_view(), name='usuarios_form'),
    


    path('insumos/', views.insumos_view, name="insumos_view"),
    path('insumos/api/', views.ApiInsumos),
    path('entrada-salida/insumos/<int:pk>', views.entrada_salida_insumos, name="entrada_salida"),
    path('insumos/<int:pk>', views.InsumosFormView.as_view(), name='insumos_form'),
    


    path('archivos/', views.archivos_view, name='archivos_view'),
    path('archivos/api/', views.ApiArchivos),
    path('archivos/compartir/<int:pk>/', views.compartir_archivo, name='compartir_archivo'),
    path('archivos/eliminar/<int:pk>/', views.eliminar_archivo, name='eliminar_archivo'),
    
    path('pacientes/', views.pacientes_view, name="pacientes_view"),
    path('pacientes/api/', views.ApiPaciente),
    path('pacientes/form/<str:pk>/', views.PacientesFormView.as_view(), name="pacientes_form"),
    

    path('pacientes/api/<str:pk>/', views.ApiSolicitud),  
    path('solicitud/<str:pk>/<str:pk_paciente>/', views.solicitud_view, name="solicitudes_form"),
    path('atencion/<str:pk>/', views.atencion_view, name="atencion_form"),
    path('atencion/usuarios/<str:pk>/', views.usuarios_solicitud_view, name="usuarios_solicitud_form"),
    path('desvincular/fono/<int:pk>', views.desvincular_fono, name="desvincular_fono"),
    path('sesion/form/<str:pk>/<str:pk_solicitud>/', views.sesion_view, name="sesion_form"),
    path('sesion/api/<str:pk>/', views.ApiSesion),
    path('sesion/eliminar/<str:pk>/', views.eliminar_sesion, name="eliminar_sesion"),
    path('upload/', views.archivo_form, name='file-upload'),
    path('listaespera/api/', views.ApiListaEspera),
    path('perfil/usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('subir/imagen/', views.subir_imagen, name='subir_imagen'),
    path('change/password/', views.change_password, name='change_password'),
    path('bloquear/usuario/<str:pk>/', views.bloquear_usuario, name='bloquear_usuario'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cafuv/sesiones/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import date
import uuid
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Usuario(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to='usuarios/', default='usuarios/default.png')
    phone = models.CharField(max_length=15, blank=True, null=True)
    loggin = models.BooleanField(default=False)
    tutorial = models.BooleanField(default=True)
    archivos = models.ManyToManyField('Archivo', related_name='usuarios', blank=True)
    eventos = models.ManyToManyField('Evento', related_name='usuarios', blank=True)

    

class Archivo(models.Model):
    nombre = models.CharField(max_length=25, blank=True, null=True)
    extension = models.CharField(max_length=10, blank=True, null=True)
    fecha = models.DateField(auto_now_add=True)
    archivo = models.FileField(upload_to='archivos/', default='archivos/default.png')

    @property
    def propietario(self):
        usuario = self.usuarios.first()
        return usuario.username

class Evento(models.Model):
    titulo = models.CharField(max_length=25, blank=False, null=False)
    descripcion = models.TextField(blank=True, null=True)
    fecha_inicio = models.DateTimeField(blank=False, null=False)
    fecha_termino = models.DateTimeField(blank=True, null=True)
    creador = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, blank=True, null=True)
    opciones = (
        ('FF0000', 'Alta'),
        ('FFFF00', 'Media'),
        ('00FF00', 'Baja'),
    )
    prioridad = models.CharField(max_length=6, choices=opciones, default="00FF00", blank=False, null=False)


class Insumo(models.Model):
    nombre = models.CharField(max_length=25, null=False, blank=False)
    descripcion = models.TextField(blank=True, null=True)
    cantidad = models.PositiveIntegerField(default=0)
    opciones = (
        ('No aplica', 'No aplica'),
        ('Nuevo', 'Nuevo'),
        ('Usado', 'Usado'),
    )
    estado = models.CharField(max_length=25, choices=opciones, blank=False, null=False)


class EntradaSalidaInsumo(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    insumo = models.ForeignKey(Insumo, on_delete=models.DO_NOTHING)
    cantidad = models.PositiveIntegerField(default=1)
    fecha = models.DateTimeField(auto_now_add = True)
    tipo = models.CharField(max_length=1, null=False, default="+")


class Comuna(models.Model):
    nombre = models.CharField(max_length=50, blank=False, null=False)
    
    def __str__(self):
        return self.nombre

class Paciente(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rut = models.CharField(max_length=10, unique=True, blank=False, null=False)
    nombre = models.CharField(max_length=50, blank=False, null=False)
    apellido = models.CharField(max_length=50, blank=False, null=False)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    comuna = models.ForeignKey(Comuna, on_delete=models.DO_NOTHING, blank=True, null=True, default=1)
    telefono = models.CharField(max_length=15, blank=False, null=False)
    email = models.EmailField(blank=True, null=True)
    opciones = (
        ('Nulo', 'Prefiero no decirlo'),
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
    )
    genero = models.CharField(max_length=9, choices=opciones, blank=False, null=False)

    def __str__(self):
        return f"{self.rut} - {self.nombre} {self.apellido}"

    def calcular_edad(self):
        today = date.today()
        age = today.year - self.fecha_nacimiento.year - \
            ((today.month, today.day) <
             (self.fecha_nacimiento.month, self.fecha_nacimiento.day))
        return age

    @property
    def edad(self):
        return self.calcular_edad()

class Cargo(models.Model):
    nombre = models.CharField(max_length=50, blank=False, null=False, unique=True)



from datetime import datetime
from django.utils import timezone


class Atencion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fecha = models.DateTimeField(blank=False, null=True)
    diagnostico = models.CharField(max_length=50, blank=True, null=True)
    enfoque = models.CharField(max_length=30, blank=True, null=True)
    objetivo_general = models.CharField(max_length=100, blank=True, null=True)
    solicitud = models.OneToOneField('Solicitud', on_delete=models.DO_NOTHING, blank=False, null=False)

    @property
    def mes(self):
        return self.fecha.strftime("%B")
    
    @property
    def fecha_input(self):
        local_fecha = self.fecha.astimezone(timezone.get_current_timezone())
        value = local_fecha.strftime("%Y-%m-%dT%H:%M")
        return value if value != "None" else ""
    
    @property
    def fecha_format(self):
        local_fecha = self.fecha.astimezone(timezone.get_current_timezone())
        value = local_fecha.strftime("%d/%m/%Y - %H:%M")
        return value if value != "None" else ""

class Solicitud(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fecha = models.DateTimeField(auto_now_add=True)
    motivo = models.CharField(max_length=255, blank=False, null=False)
    paciente = models.ForeignKey(Paciente, on_delete=models.DO_NOTHING, blank=True, null=True)

    @property
    def fecha_input(self):
        local_fecha = self.fecha.astimezone(timezone.get_current_timezone())
        value = local_fecha.strftime("%d/%m/%Y - %H:%M")
        return value if value != "None" else ""
    

    
class UsuarioSolicitud(models.Model):
    cargo = models.ForeignKey(Cargo, on_delete=models.DO_NOTHING, blank=True, null=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, blank=True, null=True)
    solicitud = models.ForeignKey(Solicitud, on_delete=models.DO_NOTHING, blank=True, null=True)

class Sesion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fecha = models.DateTimeField(null=False, blank=False)
    numero = models.PositiveIntegerField(null=False, blank=False)
    tiempo = models.PositiveIntegerField(null=True, blank=True)
    area = models.CharField(max_length=30, null=False, blank=False)
    objetivo = models.CharField(max_length=255, null=False, blank=False)
    material = models.CharField(max_length=30, null=False, blank=False)
    atencion = models.ForeignKey(Atencion, on_delete=models.DO_NOTHING, blank=True, null=True)
    respuesta = models.TextField(null=True, blank=True)

    @property
    def fecha_input(self):
        local_fecha = self.fecha.astimezone(timezone.get_current_timezone())
        value = local_fecha.strftime("%Y-%m-%dT%H:%M")
        return value if value != "None" else ""
    
    @property
    def fecha_format(self):
        local_fecha = self.fecha.astimezone(timezone.get_current_timezone())
        value = local_fecha.strftime("%d/%m/%Y - %H:%M")
        return value if value != "None" else ""
    

Cafuv/sesiones/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Usuario, Insumo, Evento, Paciente, Archivo, EntradaSalidaInsumo
from django.contrib.auth.models import Group


class UsuarioChangeForm(UserChangeForm):
    grupos = Group.objects.all()
    grupo_choices = [(group.name, group.name) for group in grupos]
    grupo = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-input'}),
        choices=grupo_choices,
        label="Tipo Usuario"
    )

    class Meta:
        model = Usuario
        fields = ('username', 'first_name', 'last_name',
                  'email', 'phone', 'grupo')
        # Excluir los campos de contraseña
        exclude = ('password1', 'password2',)

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input', 'oninput': "calcular_dv('id_username')"}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
            'phone': forms.TextInput(attrs={'class': 'form-input'}),
        }

        labels = {
            'username': "Rut",
            'first_name': "Nombre(s)",
            'last_name': "Apellido(s)",
            'email': "Correo Electrónico",
            'phone': "Teléfono Contacto",
        }


class ArchivoForm(forms.Form):
    file = forms.FileField()


class UsuarioForm(UserCreationForm):
    grupos = Group.objects.all()
    grupo_choices = [(group.name, group.name) for group in grupos]
    grupo = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-input'}), choices=grupo_choices, label="Tipo Usuario")

    class Meta:
        model = Usuario
        fields = ('username', 'first_name', 'last_name', 'email',
                  'phone', 'grupo', 'password1', 'password2')
        widgets = {
            'password1': forms.HiddenInput(),
            'password2': forms.HiddenInput(),
            'username': forms.TextInput(attrs={'class': 'form-input', 'oninput': "calcular_dv('id_username')"}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
            'phone': forms.TextInput(attrs={'class': 'form-input'}),
            'grupo': forms.Select(attrs={'class': 'form-input'}),
        }

        labels = {
            'username': "Rut",
            'first_name': "Nombre(s)",
            'last_name': "Apellido(s)",
            'email': "Correo Electrónico",
            'phone': "Teléfono Contacto",
            'grupo': "Tipo Usuario",
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        user_instance = getattr(self, 'instance', None)

        # Verificar si el nombre de usuario ha cambiado
        if user_instance and user_instance.username == username:
            return username  # Si no ha cambiado, retornar el mismo valor

        # Verificar si el nombre de usuario ya existe en otro usuario
        if Usuario.objects.filter(username=username).exists():
            raise forms.ValidationError('El nombre de usuario ya está en uso.')

        return username  # Retornar el nombre de usuario si no existe en otro usuario


class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ('titulo', 'fecha_inicio', 'fecha_termino',
                  'descripcion', 'prioridad')
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-input'}),
            'fecha_inicio': forms.DateTimeInput(attrs={'type': 'text', 'onfocus': 'convertir_tipo("id_fecha_inicio", "datetime-local")', 'onblur': 'convertir_tipo("id_fecha_inicio", "text")', 'onchange': 'validar_fecha_hora("id_fecha_inicio")'}),
            'fecha_termino': forms.DateTimeInput(attrs={'type': 'text', 'onfocus': 'convertir_tipo("id_fecha_termino", "datetime-local")', 'onblur': 'convertir_tipo("id_fecha_termino", "text")', 'onchange': 'validar_fecha_hora_termino("id_fecha_termino")'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-input'}),
            'prioridad': forms.Select(attrs={'required': ''})
        }
        labels = {
            'titulo': "Título",
            'fecha_inicio': "Fecha de inicio",
            'fecha_termino': "Fecha de término",
            'descripcion': "Descripción",
            'prioridad': "Prioridad",
        }

    usuarios = forms.ModelMultipleChoiceField(
        queryset=Usuario.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label='Usuarios',
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['usuarios'].initial = self.instance.usuarios.all()


class PacienteForm(forms.ModelForm):

    class Meta:
        model = Paciente
        fields = ['rut', 'nombre', 'apellido', 'fecha_nacimiento',
                  'comuna', 'genero', 'telefono', 'email']
        widgets = {
            'rut': forms.TextInput(attrs={'oninput': "calcular_dv('id_rut')"}),
            'nombre': forms.TextInput(),
            'apellido': forms.TextInput(),
            'fecha_nacimiento': forms.DateInput(attrs={'onchange': "validar_fecha_menor('id_fecha_nacimiento')"}),
            'comuna': forms.Select(attrs={'required': ''}),
            'genero': forms.Select(attrs={'required': ''}),
            'telefono': forms.TextInput(attrs={'required': ''}),
            'email': forms.EmailInput(attrs={'required': ''})
        }

    def __init__(self, *args, **kwargs):
        super(PacienteForm, self).__init__(*args, **kwargs)
        self.fields['rut'].label = 'RUT'
        self.fields['nombre'].label = 'Nombre(s)'
        self.fields['apellido'].label = 'Apellido(s)'
        self.fields['fecha_nacimiento'].label = 'Fecha de nacimiento'
        self.fields['comuna'].label = 'Comuna'
        self.fields['genero'].label = 'Género'
        self.fields['telefono'].label = 'N° Contacto'
        self.fields['email'].label = 'Correo Electrónico'
        self.fields['genero'].choices = [('Nulo', 'Prefiero no decirlo'), (
            'Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')]


class InsumoForm(forms.ModelForm):
    class Meta:
        model = Insumo
        fields = ('nombre', 'descripcion', 'cantidad', 'estado')
        widgets = {
            'nombre': forms.TextInput(),
            'descripcion': forms.Textarea(),
            'cantidad': forms.NumberInput(),
            'estado': forms.Select(attrs={'required': ''}),
        }
        labels = {
            'nombre': "Nombre",
            'descripcion': "Descripción",
            'cantidad': "Cantidad",
            'estado': "Estado"
        }

    def __init__(self, *args, **kwargs):
        super(InsumoForm, self).__init__(*args, **kwargs)
        self.fields['estado'].choices = [
            ('No aplica', 'No aplica'),
            ('Nuevo', 'Nuevo'),
            ('Usado', 'Usado'),
        ]

Cafuv/sesiones/templates/forms/atencion.html
{% extends 'base.html' %}

{% block title %}
<h1>
    <i class="fa-solid fa-user-group"></i> 
    <a href="{% url 'pacientes_form' pk=solicitud.paciente.id %}" style="color:#1e1e1e">Perfil paciente {{solicitud.paciente.nombre}} {{solicitud.spaciente.apellido}}</a>
    <i class="fa-solid fa-chevron-right"></i>
    Solicitud
</h1>
{% endblock title %}
{% block active-paciente %}active{% endblock active-paciente %}
{% block content %}
<div class="plan">
    <div>
        <h3>Paciente</h3>

        <div>
            <label>Nombre</label>
            <div class="form-edit-box">
                <input value="{{solicitud.paciente.nombre}} {{solicitud.paciente.apellido}}" disabled>
            </div>
        </div>
        <div>
            <label>Edad</label>
            <div class="form-edit-box">
                <input value="{{solicitud.paciente.edad}}" disabled>
            </div>
        </div>
        <div class="fonos">
            <h3>Fonoaudiólogos</h3>
            <a href="{% url 'usuarios_solicitud_form' pk=solicitud.id %}" class="btn">Asignar fonoaudiólogo +</a>
        </div>
        {% for x in fonos %}
        {{x.usuario.first_name}} {{x.usuario.last_name}} - {{x.cargo.nombre}} <a href="{% url 'desvincular_fono' pk=x.id %}"><i class="fa-solid fa-trash" style="color:red"></i></a><br>
        {% endfor %}
    </div>
    {% if atencion %}
    <form method="post" id="form_atencion">
        {% csrf_token %}
        <h3>Plan de Tratamiento</h3>
        <label>Fecha de atención</label>
        <div class="form-edit-box">
            <input disabled name="fecha" id="id_fecha" type="datetime-local" onchange="validar_fecha(this)" value="{{atencion.fecha_input}}">
            <i class="fa-solid fa-pen-to-square btn-edit" onclick="alternar_estado('id_fecha')"></i>
        </div>

        <span id="fecha_alert" class="alert"></span>
        <label>Diagnóstico</label>
        <div class="form-edit-box">
            <input disabled name="diagnostico" id="id_diagnostico" type="text" value="{% if solicitud.atencion.diagnostico != None %}{{solicitud.atencion.diagnostico}}{% endif %}">
            <i class="fa-solid fa-pen-to-square btn-edit" onclick="alternar_estado('id_diagnostico')"></i>
        </div>

        <label>Enfoque</label>
        <div class="form-edit-box">
            <input disabled name="enfoque" id="id_enfoque" type="text" value="{% if solicitud.atencion.diagnostico != None %}{{solicitud.atencion.enfoque}}{% endif %}">
            <i class="fa-solid fa-pen-to-square btn-edit" onclick="alternar_estado('id_enfoque')"></i>
        </div>

        <label>Objetivo general</label>
        <div class="form-edit-box">
            <input disabled name="objetivo_general" id="id_objetivo_general" type="text" value="{% if solicitud.atencion.diagnostico != None %}{{solicitud.atencion.objetivo_general}}{% endif %}">
            <i class="fa-solid fa-pen-to-square btn-edit" onclick="alternar_estado('id_objetivo_general')"></i>
        </div>

        <button class="btn" type="button" onclick="activar_inputs()" style="margin-top:50px;">Guardar</button>
    </form>
    <script>
        function activar_inputs() {
            document.getElementById('id_fecha').disabled = false;
            document.getElementById('id_diagnostico').disabled = false;
            document.getElementById('id_enfoque').disabled = false;
            document.getElementById('id_objetivo_general').disabled = false;
            document.getElementById('form_atencion').submit();
        }
    </script>
    {% else %}
    <form method="post">
        {% csrf_token %}
        <h3>Plan de Tratamiento</h3>

        <div class="form-box" style="margin-top:30px;">
            <input name="fecha" id="id_fecha" type="datetime-local" onchange="validar_fecha(this)">
            <label class="label-input" for="id_apellido">Fecha de atención</label>
        </div>
        <span id="fecha_alert" class="alert"></span>
        <p>Para continuar con el proceso debes asignar una fecha.</p>

        <button class="btn" type="submit">Guardar</button>
    </form>
    {% endif %}
</div>
{% if atencion %}
<div style="display:flex; justify-content:center; padding:50px; flex-direction:column; align-items:center;">
    <h3>Plan Operacional</h3>
    <a href="{% url 'sesion_form' pk=0 pk_solicitud=solicitud.id %}" class="btn" style="width:200px;text-align:center;">Agregar Sesión +</a>
</div>
{% endif %}

<div style="padding:50px; padding-top:0px;">
    {% if atencion %}
    <div id="sesiones"></div>
    {% else %}
    <p>Debes asignar una fecha para planificar las sesiones del plan operacional</p>
    {% endif %}
</div>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        fetch('/sesion/api/{{solicitud.id}}/')
            .then(response => response.json())
            .then(data => {
                new gridjs.Grid({
                    search: true,
                    sort: true,
                    resizable: true,
                    columns: [
                        'Fecha',
                        'N° Sesión',
                        'Tiempo',
                        'Área',
                        'Objetivo Operacional',
                        'Materiales',
                        'Respuesta',
                        {
                            name: 'Acciones',
                            formatter: (cell) => gridjs.html(`<div class="container-table-button"><a class='btn bg-secondary' href='/sesion/form/${cell}/{{solicitud.id}}/'><i class="fa-solid fa-pen-to-square"></i></a><a class='btn bg-danger' href='/sesion/eliminar/${cell}'><i class='fa fa-trash'></i></a></div>`)
                        }
                    ],
                    data: data,
                    language: {
                        'search': {
                            'placeholder': 'Buscar...'
                        },
                    }
                }).render(document.getElementById("sesiones"));
            })
            .catch(error => {
                console.error('Error:', error);
            });
    });




</script>
{% endblock content %}

{% block form %}
{% block form-paciente %}
{% endblock %}
{% endblock form %}

Cafuv/sesiones/templates/forms/pacientes_form.html
{% extends 'pages/pacientes.html' %}
{% load static %}
{% block form-paciente %}
<i class="fa-solid fa-circle-info" style="font-size:25px; position: absolute; top:20px; right:20px; color:var(--primary)" onclick="tutorial_info_paciente()"></i>

<div class="form-back">
    <div class="form-container">
        <div class="form-header">
            <h2>Nuevo Paciente</h2>
            <a href="{% url 'pacientes_view' %}"><i class="fa-solid fa-x"></i></a>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="rut-container">
                <div class="form-box">
                    {{ form.rut }}
                    <label class="label-input" for="id_rut">{{ form.rut.label }}</label>
                </div>
                <i class="fa fa-minus"></i>
                <input class="disabled" type="text" id="dv" name="inputDv" disabled>
            </div>
            <div class="form-box">
                {{ form.nombre }}
                <label class="label-input" for="id_label">{{ form.nombre.label }}</label>
            </div>
            <div class="form-box">
                {{ form.apellido }}
                <label class="label-input" for="id_apellido">{{ form.apellido.label }}</label>
            </div>
            <div class="form-box">
                {{ form.fecha_nacimiento }}
                <label class="label-input" for="id_fecha_nacimiento">{{ form.fecha_nacimiento.label }}</label>
            </div>
            <div class="form-box">
                {{ form.comuna }}
                <label class="label-input" for="id_comuna">{{ form.comuna.label }}</label>
            </div>
            <div class="form-box">
                {{ form.genero }}
                <label class="label-input" for="id_genero">{{ form.genero.label }}</label>
            </div>
            <div class="telefono-container">
                <input class="disabled" type="text" value="+56" disabled>
                <div class="form-box">
                    {{ form.telefono }}
                    <label class="label-input" for="id_telefono">{{ form.telefono.label }}</label>
                </div>
            </div>
            <div class="form-box">
                {{ form.email }}
                <label class="label-input" for="id_email">{{ form.email.label }}</label>
            </div>
            <button class="btn" type="submit">Guardar</button>
        </form>
    </div>
</div>
<script>
    const fechaNacimientoInput = document.getElementById("id_fecha_nacimiento")
    fechaNacimientoInput.addEventListener('focus', function (event) {
        fechaNacimientoInput.type = "date"
    });
    fechaNacimientoInput.addEventListener('blur', function (event) {
    fechaNacimientoInput.type = "text";
});
</script>
{% endblock form-paciente %}

Cafuv/sesiones/templates/forms/sesion.html
{% extends 'forms/atencion.html' %}
{% load static %}


{% block form-paciente %}
<div class="form-back">
    <div class="form-container">
        <div class="form-header">
            {% if sesion %}
            <h2>Editar Sesión</h2>
            {% else %}
            <h2>Nueva Sesión</h2>
            {% endif %}
            <a href="{% url 'atencion_form' pk=solicitud.id %}"><i class="fa-solid fa-x"></i></a>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-box" style="margin-top:30px;">
                <input name="fecha" id="id_fecha" type="datetime-local" value="{{sesion.fecha_input}}" onchange="validar_fecha(this)">
                <label class="label-input" for="id_apellido">Fecha de atención</label>
            </div>
            <span id="fecha_alert" class="alert"></span>
            <div class="form-box">
                <input name="tiempo" id="id_tiempo" type="number" value="{{sesion.tiempo}}" onchange="validar_positivo(this)">
                <label class="label-input" for="id_tiempo">Duración (Minutos)</label>
            </div>
            <p id="positive_alert"></p>
            <div class="form-box">
                <input name="area" id="id_area" type="text" value="{{sesion.area}}">
                <label class="label-input" for="id_area">Área</label>
            </div>
            <div class="form-box">
                <input name="objetivo" id="id_objetivo" type="text" value="{{sesion.objetivo}}">
                <label class="label-input" for="id_objetivo">Objetivo</label>
            </div>
            <div class="form-box">
                <input name="material" id="id_material" type="text" value="{{sesion.material}}">
                <label class="label-input" for="id_material">Material</label>
            </div>
            <div class="form-box">
                <textarea name="respuesta" id="id_respuesta" type="text">{{sesion.respuesta}}</textarea>
                <label class="label-input" for="id_respuesta">Respuesta</label>
            </div>

            <button class="btn" type="submit">Guardar</button>
        </form>
    </div>
</div>
{% endblock form-paciente %}